### ISSUE TITLE
I was not able to find documentation for code42.backup.manifest.ArchiveUnavailableException

### ISSUE THREAD

**Issue by cjohnson318** [code42/crashplan_api_examples#17]
I tried to make a GET request to the WebRestoreTreeNode and got a weird response:

    [{u'name': u'SYSTEM', u'description': u'com.code42.backup.manifest.ArchiveUnavailableException'}]

I wasn't able to find any documentation for this response. I am using the 3.6.4 Enterprise edition.

**Comment by akader** [comment]
Hi Connor,
I just posted my python example of doing a pushRestore.  I created it in a fork of the api examples:
https://github.com/akader/crashplan_api_examples because there are 3 minor additions to AJ's c42SharedLibrary.  I just tested this on 4.1.6 and it works but haven't tested it on 3.6.x.

C O D E 4 2
-
Amir Kader
enterprise systems engineer
cell: 312-218-7853

**Comment by cjohnson318** [comment]
Hi Amir,

Thanks again! I'll see if I can use your script to get a similar thing to work with 3.6.4. I'll let you know how it goes.

Thanks again,

Connor Johnson
