### ISSUE TITLE
How to determine when PushRestore is finished?

### ISSUE THREAD

**Issue by sarahs** [code42/crashplan_api_examples#26]
I'm using a modified version of the PushRestore script that is working well and resulting in restored test files very quickly. But I can't figure out how to programmatically determine when the restore job is done.

The PushRestore response gives me a restoreId, but when I plug that value into `/api/RestoreRecord/<restoreId>`, I get this: `"description": "Record of restore not found"`

Is there another way? If I query `/api/RestoreRecord/` without any parameters, I do get a list of total restores for my organization, but none of the restoreIDs in that list correspond to my successful pushRestore tests. 

Thanks for any help!

**Comment by toddojala** [comment]
Sarah: 
This sounds like a bug. If your push restores are indeed occurring, but you can't find the restore ID using RestoreRecord, then.. it's a bug, or by design.
I do know that there is really know way to know, currently, when a push restore is completed. That is a feature that we may at some point add. For now, it prevents us or anyone else from checking on that status.
Best,
Todd Ojala
Pro Services at Code42

**Comment by sarahs** [comment]
Thanks Todd! Good to know. I'm sure I can find a workaround.
